import React from 'react';
import {
  AlignLeft,
  ArrowDownAZ,
  ArrowLeft,
  ArrowRight,
  Award,
  Baby,
  BadgeCheck,
  Ban,
  BarChart3,
  BellRing,
  BookA,
  BookOpen,
  Bookmark,
  Brain,
  CalendarCheck,
  CalendarClock,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  CircleSlash,
  ClipboardList,
  Clock,
  Coffee,
  Compass,
  Copy,
  Dices,
  DraftingCompass,
  Droplet,
  Dumbbell,
  Flame,
  Gamepad2,
  GraduationCap,
  Heart,
  Home,
  Hourglass,
  Infinity,
  Info,
  Landmark,
  Languages,
  Leaf,
  Lightbulb,
  Link,
  ListOrdered,
  Lock,
  Map,
  Medal,
  MessageCircle,
  MessagesSquare,
  Moon,
  Mountain,
  MousePointerClick,
  Network,
  Package,
  Palette,
  PartyPopper,
  Pencil,
  PenLine,
  Play,
  PlayCircle,
  Puzzle,
  RefreshCw,
  Route,
  Rows3,
  ScrollText,
  Search,
  Settings,
  Shapes,
  Share2,
  Shield,
  Shuffle,
  SlidersHorizontal,
  Snowflake,
  Sparkles,
  Speech,
  SpellCheck,
  Star,
  Target,
  TrendingUp,
  Type,
  User,
  Users,
  Volume2,
  Waves,
  Waypoints,
  Wrench,
  X,
} from 'lucide-react';

const MATERIAL_ICON_MAP = {
  ac_unit: Snowflake,
  ads_click: MousePointerClick,
  all_inclusive: Infinity,
  architecture: DraftingCompass,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  assignment: ClipboardList,
  auto_awesome: Sparkles,
  auto_stories: BookOpen,
  bar_chart: BarChart3,
  block: Ban,
  bookmark: Bookmark,
  build: Wrench,
  calendar_month: CalendarCheck,
  casino: Dices,
  category: Shapes,
  celebration: PartyPopper,
  center_focus_strong: Target,
  chat_bubble: MessageCircle,
  check: Check,
  check_circle: CircleCheck,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  child_care: Baby,
  close: X,
  coffee: Coffee,
  content_copy: Copy,
  conversion_path: Waypoints,
  dark_mode: Moon,
  dictionary: BookA,
  done_all: CheckCheck,
  east: ArrowRight,
  eco: Leaf,
  edit: Pencil,
  emoji_events: Award,
  error: CircleAlert,
  event_available: CalendarCheck,
  event_repeat: CalendarClock,
  expand_less: ChevronUp,
  expand_more: ChevronDown,
  explore: Compass,
  extension: Puzzle,
  favorite: Heart,
  fitness_center: Dumbbell,
  format_align_left: AlignLeft,
  format_list_numbered: ListOrdered,
  forum: MessagesSquare,
  foundation: Landmark,
  groups: Users,
  history_edu: ScrollText,
  home: Home,
  hourglass_empty: Hourglass,
  hub: Network,
  info: Info,
  ink_pen: PenLine,
  inventory_2: Package,
  keyboard_arrow_down: ChevronDown,
  keyboard_arrow_left: ChevronLeft,
  keyboard_arrow_right: ChevronRight,
  keyboard_arrow_up: ChevronUp,
  landscape: Mountain,
  language: Languages,
  lightbulb: Lightbulb,
  link: Link,
  local_cafe: Coffee,
  local_fire_department: Flame,
  lock: Lock,
  map: Map,
  menu_book: BookOpen,
  motion_photos_off: CircleSlash,
  notifications_active: BellRing,
  palette: Palette,
  person: User,
  play_arrow: Play,
  play_circle: PlayCircle,
  psychiatry: Brain,
  quiz: CircleHelp,
  radio_button_unchecked: Circle,
  record_voice_over: Speech,
  restart_alt: RefreshCw,
  route: Route,
  schedule: Clock,
  school: GraduationCap,
  search: Search,
  settings: Settings,
  share: Share2,
  shield: Shield,
  shuffle: Shuffle,
  sort_by_alpha: ArrowDownAZ,
  spellcheck: SpellCheck,
  star: Star,
  stars: Star,
  target: Target,
  task_alt: BadgeCheck,
  text_fields: Type,
  text_format: Type,
  trending_up: TrendingUp,
  tune: SlidersHorizontal,
  videogame_asset: Gamepad2,
  view_stream: Rows3,
  volume_up: Volume2,
  water: Droplet,
  waves: Waves,
  workspace_premium: Medal,
};

export default function Icon({
  name,
  children,
  className = '',
  size = 24,
  strokeWidth = 2.4,
  filled = false,
  fallback = null,
  ...props
}) {
  const iconName = name || children;
  const SvgIcon = MATERIAL_ICON_MAP[iconName];

  if (SvgIcon) {
    return (
      <SvgIcon
        aria-hidden="true"
        className={`app-icon ${className}`.trim()}
        size={size}
        strokeWidth={strokeWidth}
        fill={filled ? 'currentColor' : 'none'}
        {...props}
      />
    );
  }

  if (fallback) return fallback;

  return (
    <span
      className={`material-symbols-outlined ${className}`.trim()}
      style={{ fontVariationSettings: `'FILL' ${filled ? 1 : 0}, 'wght' 500, 'GRAD' 0, 'opsz' 24` }}
      aria-hidden="true"
      {...props}
    >
      {iconName}
    </span>
  );
}
