import React from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import App from './App.jsx';
import './index.css';
import './styles/main.css';

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <BrowserRouter>
      <App />
    </BrowserRouter>
  </React.StrictMode>
);

// Register service worker (generated by Vite PWA plugin)
if ('serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    // The service worker will be automatically registered by vite-plugin-pwa
    // This import is used for development mode PWA support
    import('virtual:pwa-register').then(({ registerSW }) => {
      registerSW({
        onNeedRefresh() {
          console.log('[PWA] New content available, please refresh.');
          // You could show a toast notification here
        },
        onOfflineReady() {
          console.log('[PWA] App ready to work offline');
        },
        onRegistered(registration) {
          console.log('[PWA] Service Worker registered', registration);
        },
        onRegisterError(error) {
          console.error('[PWA] Service Worker registration failed', error);
        }
      });
    }).catch(error => {
      // In production, the service worker is registered via index.html
      console.log('[PWA] Using production service worker registration');
    });
  });
}
